title = "Sjnecura"
baseURL = "/"
languageCode = "en-us"
theme = "ananke"
# copyright = "CC-BY"
# themesDir = "../.."

DefaultContentLanguage = "it"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
# googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = true
      unsafe = true
      xHTML = true

[params]
  show_reading_time = true
  author = "Claudio Carboncini"
  favicon = ""
  site_logo = ""
  description = "Appunti disordinati sul software libero"
  facebook = ""
  twitter = ""
  instagram = ""
  youtube = ""
  github = "https://github.com/karbonk"
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  custom_css = ["css/custom.css"]
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "images/bannerwp.jpg"
  recent_posts_number = 2
